version: '3'
volumes:
  postgres_data:
    driver: local
  ldap_data:
    driver: local
services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    links:
      - ldapservice:ldap-service
    ports:
      - 8080:8080
    depends_on:
      - postgres
  ldapservice:
    image: osixia/openldap:1.3.0
    volumes:
      - ldap_data://var/lib/ldap
    environment:
      LDAP_ORGANISATION: testOrg
      LDAP_DOMAIN: ldap-service
      LDAP_ADMIN_PASSWORD: password
    ports:
      - 389:389
      - 636:636
  ldapgui:
    image: osixia/phpldapadmin:0.9.0
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap-service
    links:
      - ldapservice:ldap-service
    ports:
      - 6443:443
    depends_on:
      - ldapservice